site_name: Prévision de la Demande Énergétique
site_description: "Documentation du projet académique de prévision de la demande électrique en Espagne"
repo_url: https://github.com/Marc1T/electricityDemandForecasting.git

theme:
  name: material
  features:
    - navigation.instant

nav:
  - Accueil: index.md
  - Introduction: intro.md
  - Données: data.md
  - Modèles: models.md
  - Résultats: results.md
  - Dashboard: dashboard.md
  - Équipe: team.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
